server:
  port: 1234

spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.microservice.inventory_service.event.OrderCreatedEvent

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.microservice.inventory_service: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      inventoryService:
        maxAttempts: 3
        waitDuration: 2s
